#!/bin/bash

# Install HAProxy
apt-get update
apt-get install -y haproxy

# Create the HAProxy configuration file
cat << EOF > /etc/haproxy/haproxy.cfg
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 64617-web-01 52.201.219.192:80 check
    server 64617-web-02 100.25.143.187:80 check

EOF

# Set the hostnames of the servers
echo "64617-web-01" > /etc/hostname
hostname -F /etc/hostname
echo "52.201.219.192 64617-web-01" >> /etc/hosts
echo "100.25.143.187 64617-web-02" >> /etc/hosts

# Start the HAProxy service
systemctl start haproxy

# Enable the HAProxy service to start on boot
systemctl enable haproxy

