#!/usr/bin/env bash
#Prints bad luck, good luck or Best School
i=0
while [ $i -lt 10 ]
do
    if [ $i -eq 3 ]
    then
	echo 'bad luck'
    elif [ $i -eq 7 ]
    then
	echo 'good luck'
    else
	echo "Best School"
    fi
    let i=i+1
done
